agency/urls.py
from django.urls import path

from agency.views import (
    index,
    TopicListView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    NewspaperListView,
    NewspaperDetailView,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    RedactorListView,
    RedactorDetailView,
    RedactorCreateView,
    RedactorUpdateView,
    RedactorDeleteView,
    ToggleAssignToNewspaperView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "topics/",
        TopicListView.as_view(),
        name="topic-list",
    ),
    path(
        "topics/create/",
        TopicCreateView.as_view(),
        name="topic-create",
    ),
    path(
        "topics/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update",
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete",
    ),
    path("newspapers/", NewspaperListView.as_view(), name="newspaper-list"),
    path(
        "newspapers/<int:pk>/", NewspaperDetailView.as_view(), name="newspaper-detail"
    ),
    path("newspapers/create/", NewspaperCreateView.as_view(), name="newspaper-create"),
    path(
        "newspapers/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update",
    ),
    path(
        "newspapers/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete",
    ),
    path(
        "newspapers/<int:pk>/toggle-assign/",
        ToggleAssignToNewspaperView.as_view(),
        name="toggle-newspaper-assign",
    ),
    path("redactors/", RedactorListView.as_view(), name="redactor-list"),
    path("redactors/<int:pk>/", RedactorDetailView.as_view(), name="redactor-detail"),
    path("redactors/", RedactorListView.as_view(), name="redactor-list"),
    path("redactors/<int:pk>/", RedactorDetailView.as_view(), name="redactor-detail"),
    path("redactors/create/", RedactorCreateView.as_view(), name="redactor-create"),
    path(
        "redactors/<int:pk>/update/",
        RedactorUpdateView.as_view(),
        name="redactor-update",
    ),
    path(
        "redactors/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete",
    ),
]

app_name = "agency"

inform_agency/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("agency.urls", namespace="agency")),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

agency/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Topic(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Redactor(AbstractUser):
    years_of_experience = models.IntegerField()

    class Meta:
        ordering = ["username"]

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    published_date = models.DateTimeField(auto_now_add=True)
    topic = models.ManyToManyField(Topic, related_name="newspapers")
    redactor = models.ManyToManyField(Redactor, related_name="newspapers")

    class Meta:
        ordering = ["-published_date"]

    def __str__(self):
        return self.title

agency/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from agency.models import Topic, Newspaper, Redactor


class RedactorUsernameSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by username", "class": "form-control"}
        ),
    )


class TopicSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by name", "class": "form-control"}
        ),
    )


class NewspaperTitleSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by title", "class": "form-control"}
        ),
    )


class NewspaperForm(forms.ModelForm):
    redactor = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    topic = forms.ModelMultipleChoiceField(
        queryset=Topic.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    content = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control"}))
    title = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))

    class Meta:
        model = Newspaper
        fields = "__all__"


class RedactorCreationForm(UserCreationForm):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    last_name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
    username = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
    years_of_experience = forms.IntegerField(
        widget=forms.NumberInput(attrs={"class": "form-control"})
    )
    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            attrs={"label": "Password", "class": "form-control"}
        ),
    )
    password2 = forms.CharField(
        label="Confirm password",
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
    )

    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = UserCreationForm.Meta.fields + (
            "years_of_experience",
            "first_name",
            "last_name",
        )


class RedactorForm(forms.ModelForm):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    last_name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
    username = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
    years_of_experience = forms.IntegerField(
        widget=forms.NumberInput(attrs={"class": "form-control"})
    )

    class Meta:
        model = Redactor
        fields = (
            "username",
            "years_of_experience",
            "first_name",
            "last_name",
        )


class TopicForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))

    class Meta:
        model = Topic
        fields = "__all__"

agency/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic

from agency.forms import (
    TopicSearchForm,
    NewspaperTitleSearchForm,
    RedactorUsernameSearchForm,
    NewspaperForm,
    RedactorCreationForm,
    RedactorForm,
    TopicForm,
)
from agency.models import Redactor, Topic, Newspaper


@login_required
def index(request):
    """View function for the home page of the site."""

    num_redactors = Redactor.objects.count()
    num_topics = Topic.objects.count()
    num_newspapers = Newspaper.objects.count()

    context = {
        "num_redactors": num_redactors,
        "num_topics": num_topics,
        "num_newspapers": num_newspapers,
    }

    return render(request, "agency/index.html", context=context)


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TopicListView, self).get_context_data(**kwargs)
        context["search_form"] = TopicSearchForm(
            initial={"name": self.request.GET.get("name", "")}
        )
        return context

    def get_queryset(self):
        form = TopicSearchForm(self.request.GET)
        if form.is_valid():
            return Topic.objects.filter(name__icontains=form.cleaned_data["name"])
        return Topic.objects.all()


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    form_class = TopicForm
    success_url = reverse_lazy("agency:topic-list")


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    form_class = TopicForm
    success_url = reverse_lazy("agency:topic-list")


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    success_url = reverse_lazy("agency:topic-list")


class NewspaperListView(LoginRequiredMixin, generic.ListView):
    model = Newspaper
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(NewspaperListView, self).get_context_data(**kwargs)
        context["search_form"] = NewspaperTitleSearchForm(
            initial={"title": self.request.GET.get("title", "")}
        )
        return context

    def get_queryset(self):
        form = NewspaperTitleSearchForm(self.request.GET)
        if form.is_valid():
            return Newspaper.objects.filter(title__icontains=form.cleaned_data["title"])
        return Newspaper.objects.all()


class NewspaperDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newspaper


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("agency:newspaper-list")


class NewspaperUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("agency:newspaper-list")


class NewspaperDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    success_url = reverse_lazy("agency:newspaper-list")


class ToggleAssignToNewspaperView(LoginRequiredMixin, generic.View):
    def post(self, request, pk):
        redactor = get_object_or_404(Redactor, id=request.user.id)
        newspaper = get_object_or_404(Newspaper, id=pk)

        if redactor.newspapers.filter(id=newspaper.id).exists():
            redactor.newspapers.remove(newspaper)
        else:
            redactor.newspapers.add(newspaper)

        return redirect(reverse_lazy("agency:newspaper-detail", args=[pk]))


class RedactorListView(LoginRequiredMixin, generic.ListView):
    model = Redactor
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RedactorListView, self).get_context_data(**kwargs)
        context["search_form"] = RedactorUsernameSearchForm(
            initial={"username": self.request.GET.get("username", "")}
        )
        return context

    def get_queryset(self):
        form = RedactorUsernameSearchForm(self.request.GET)
        if form.is_valid():
            return Redactor.objects.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return Redactor.objects.all().order_by("username")


class RedactorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Redactor


class RedactorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Redactor
    form_class = RedactorCreationForm
    success_url = reverse_lazy("agency:redactor-list")


class RedactorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Redactor
    form_class = RedactorForm
    success_url = reverse_lazy("agency:redactor-list")


class RedactorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Redactor
    success_url = reverse_lazy("agency:redactor-list")

templates/agency/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="d-flex  flex-row align-items-end">
    <div class="page-header min-vh-50">
      <div class="container mt-5">
        <div class="row mt-5">
          <div class="text-center mx-auto">
            <h1 class="text-black-50 pt-3 mt-n5">
              InfoStruct
            </h1>
            <p class="lead text-black-50 mt-3">Our mission is to provide a comprehensive solution that organizes,
              structures, and optimizes your data for maximum efficiency.<br/> With our innovative tools, you can easily
              categorize, analyze, and share information, ensuring that your team stays informed and agile in a
              fast-paced
              environment. Discover how our platform can transform your agency's operations and elevate your
              decision-making
              process to new heights.</p>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="col-lg-9 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
        <div class="row">
          <div class="col-md-4 position-relative">
            <div class="p-3 text-center">
              <h1 class="text-gradient text-primary"><span id="state1" countTo="70">{{ num_topics }}</span>+</h1>
              <h5 class="mt-3">Topics</h5>
              <p class="text-sm">Navigating the World of Information.</p>
            </div>
            <hr class="vertical dark">
          </div>
          <div class="col-md-4 position-relative">
            <div class="p-3 text-center">
              <h1 class="text-gradient text-primary"><span id="state2" countTo="15">{{ num_newspapers }}</span>+</h1>
              <h5 class="mt-3">Newspapers</h5>
              <p class="text-sm">Your Trusted Source for News and Information.</p>
            </div>
            <hr class="vertical dark">
          </div>
          <div class="col-md-4">
            <div class="p-3 text-center">
              <h1 class="text-gradient text-primary" id="state3" countTo={{ num_redactors }}>{{ num_redactors }}</h1>
              <h5 class="mt-3">Redactors</h5>
              <p class="text-sm">Where Words Come to Life.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/agency/newspaper_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h3 class="mt-3">Delete newspaper <i>{{ newspaper.title }}</i>?</h3>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="javascript:history.go(-1)" class="btn btn-light ml-3">Cancel</a>
  </form>
{% endblock %}

templates/agency/newspaper_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="mt-3 d-flex justify-content-around">
    <a href="javascript:history.go(-1)" class="btn btn-light ml-3">back</a>
    <h3>
      {{ newspaper.title }}
    </h3>
    <div>
      <a href="{% url 'agency:newspaper-delete' pk=newspaper.id %}" class="btn btn-danger">
        Delete
      </a>
      <a href="{% url 'agency:newspaper-update' pk=newspaper.id %}" class="btn btn-light ml-3">
        Update
      </a>
    </div>
  </div>

  <h5>Published date: {{ newspaper.published_date }}</h5>
  <h3>Topics:</h3>
  <ul>
    {% for topic in newspaper.topic.all %}
      <li>{{ topic.name }}</li>
    {% endfor %}
  </ul>
  <h3>
    Redactors:
    {% if newspaper in user.newspapers.all %}
      <a href="{% url 'agency:toggle-newspaper-assign' pk=newspaper.id %}" class="btn btn-outline-danger ml-5">
        Remove me from this newspaper
      </a>
    {% else %}
      <a href="{% url 'agency:toggle-newspaper-assign' pk=newspaper.id %}" class="btn btn-outline-dark ml-5">
        Assign me to this newspaper
      </a>
    {% endif %}
  </h3>
  <ul>
    {% for redactor in newspaper.redactor.all %}
      <li><a
          href="{% url 'agency:redactor-detail' pk=redactor.id %}">{{ redactor.username }} </a>({{ redactor.first_name }} {{ redactor.last_name }})
      </li>
    {% endfor %}
  </ul>
  <hr>
  {{ newspaper.content }}

{% endblock %}

templates/agency/newspaper_form.html
{% extends "base.html" %}

{% block content %}
  <div class="text-center mx-auto">
    <h2 class="text-black-50 text-uppercase mt-3">
      {{ object|yesno:"Update,Create" }} newspaper</h2>
  </div>
  <section>
    <div class="col-lg-7 mx-auto d-flex justify-content-center flex-column">
      <div class="container py-4">
        <div class="row">
          <form action="" method="post" novalidate>
            {% csrf_token %}
            {{ form.as_p }}

            <input type="submit" value="Submit" class="btn bg-gradient-dark">
            <a href="javascript:history.go(-1)" class="btn btn-light ml-3">Cancel</a>
          </form>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/agency/newspaper_list.html
{% extends "base.html" %}

{% block content %}
  <div class="text-center mx-auto mt-3">
    <h1 class="text-black-50">
      Newspaper list
      <a href="{% url 'agency:newspaper-create' %}" class="btn btn-sm  btn-dark  btn-round mb-0 me-1 ml-5">
        +
      </a>
    </h1>
  </div>
  {% include "includes/search_form.html" %}
  {% if newspaper_list %}
    <ul>
      {% for newspaper in newspaper_list %}
        <li>
          <a href="{% url "agency:newspaper-detail" pk=newspaper.id %}">{{ newspaper.title }}</a>
          ({{ newspaper.published_date }})
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no newspapers for the moment</p>
  {% endif %}
{% endblock %}

templates/agency/redactor_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h3 class="mt-3">Delete redactor <i>{{ redactor.username }}</i>?</h3>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="javascript:history.go(-1)" class="btn btn-light ml-3">Cancel</a>
  </form>
{% endblock %}

templates/agency/redactor_detail.html
{% extends "base.html" %}

{% block content %}

  <div class="container">
    <div class="d-flex justify-content-around mt-3">
      <a href="javascript:history.go(-1)" class="btn btn-light ml-3">back</a>
      <h3 class="text-black-50 mb-0 mt-2">Username: {{ redactor.username }}</h3>
      <div class="d-flex">
        <a href="{% url 'agency:redactor-delete' pk=redactor.id %}" class="btn btn-danger">
          Delete
        </a>
        <a href="{% url 'agency:redactor-update' pk=redactor.id %}" class="btn btn-light ml-3">
          Update info
        </a>
      </div>
    </div>
  </div>

  <div class="d-flex flex-column align-items-end mr-5">
    <p><strong>First name:</strong> {{ redactor.first_name }}</p>
    <p><strong>Last name:</strong> {{ redactor.last_name }}</p>
    <p><strong>Years of experience:</strong> {{ redactor.years_of_experience }}</p>
  </div>

  <div class="ml-5">
    <h4>Newspapers</h4>
    {% for newspaper in redactor.newspapers.all %}
      <hr>
      <p><strong>Title:</strong> {{ newspaper.title }}.
        <a href="{% url "agency:newspaper-detail" pk=newspaper.id %}">See more...</a></p>
      <div><p><strong>Topic:</strong></p>
        <ul>
          {% for topic in newspaper.topic.all %}
            <li>{{ topic.name }}</li>
          {% endfor %}
        </ul>
      </div>

    {% empty %}
      <p>No newspapers</p>
    {% endfor %}
  </div>
{% endblock %}

templates/agency/redactor_form.html
{% extends "base.html" %}

{% block content %}
  <div class="text-center mx-auto mt-5">
    <h1 class="text-black-50">
      {{ object|yesno:"Update,Create" }} redactor</h1>
  </div>
  <div class="col-lg-7 mx-auto d-flex justify-content-center flex-column">
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form.as_p }}

      <input type="submit" value="Submit" class="btn bg-gradient-dark">
      <a href="javascript:history.go(-1)" class="btn btn-light ml-3">Cancel</a>
    </form>
  </div>
{% endblock %}

templates/agency/redactor_list.html
{% extends "base.html" %}

{% block content %}
  <div class="text-center mx-auto mt-3">
    <h1 class="text-black-50">
      Redactor List
      <a href="{% url 'agency:redactor-create' %}" class="btn btn-sm  btn-dark  btn-round mb-0 me-1 ml-5">
        +
      </a>
    </h1>
  </div>
  {% include "includes/search_form.html" %}
  {% if redactor_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Years of experience</th>
      </tr>
      {% for redactor in redactor_list %}
        <tr>
          <td>{{ redactor.id }}</td>
          <td><a href="{% url 'agency:redactor-detail' pk=redactor.id %}">{{ redactor.username }}
            {% if user == redactor %} (Me){% endif %}</a></td>
          <td>{{ redactor.first_name }}</td>
          <td>{{ redactor.last_name }}</td>
          <td>{{ redactor.years_of_experience }}</td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no redactors at the moment.</p>
  {% endif %}
{% endblock %}

templates/agency/topic_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h3 class="mt-3">Delete topic <i>{{ topic.name }}</i>?</h3>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="javascript:history.go(-1)" class="btn btn-light ml-3">Cancel</a>
  </form>
{% endblock %}

templates/agency/topic_form.html
{% extends "base.html" %}

{% block content %}
  <div class="text-center mx-auto">
    <h2 class="text-black-50 text-uppercase mt-3">
      {{ object|yesno:"Update,Create" }} topic</h2>
    <div class="col-lg-7 mx-auto d-flex justify-content-center flex-column">
      <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Submit" class="btn bg-gradient-dark">
        <a href="javascript:history.go(-1)" class="btn btn-light ml-3">Cancel</a>
      </form>
    </div>
  </div>
{% endblock %}

templates/agency/topic_list.html
{% extends "base.html" %}

{% block content %}
  <div class="text-center mx-auto mt-3">
    <h1 class="text-black-50">
      Topic List
      <a href="{% url 'agency:topic-create' %}" class="btn btn-sm  btn-dark  btn-round mb-0 me-1 ml-5">
        +
      </a>
    </h1>
  </div>
  {% include "includes/search_form.html" %}
  {% if topic_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th></th>
        <th></th>
      </tr>

      {% for topic in topic_list %}
        <tr>
          <td>
            {{ topic.id }}
          </td>
          <td>
            {{ topic.name }}
          </td>
          <td>
            <a href="{% url 'agency:topic-update' pk=topic.id %}">
              Update
            </a>
          </td>
          <td>
            <a style="color: red"
               href="{% url 'agency:topic-delete' pk=topic.id %}">
              Delete
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
    <p>There are no topics to show.</p>
  {% endif %}
{% endblock %}