agency/urls.py
from django.urls import path

from agency.views import (
    index,
    TopicListView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    NewspaperListView,
    NewspaperDetailView,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    RedactorListView,
    RedactorDetailView,
    RedactorCreateView,
    RedactorUpdateView,
    RedactorDeleteView,
    ToggleAssignToNewspaperView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "topics/",
        TopicListView.as_view(),
        name="topic-list",
    ),
    path(
        "topics/create/",
        TopicCreateView.as_view(),
        name="topic-create",
    ),
    path(
        "topics/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update",
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete",
    ),
    path("newspapers/", NewspaperListView.as_view(), name="newspaper-list"),
    path(
        "newspapers/<int:pk>/", NewspaperDetailView.as_view(), name="newspaper-detail"
    ),
    path("newspapers/create/", NewspaperCreateView.as_view(), name="newspaper-create"),
    path(
        "newspapers/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update",
    ),
    path(
        "newspapers/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete",
    ),
    path(
        "newspapers/<int:pk>/toggle-assign/",
        ToggleAssignToNewspaperView.as_view(),
        name="toggle-newspaper-assign",
    ),
    path("redactors/", RedactorListView.as_view(), name="redactor-list"),
    path("redactors/<int:pk>/", RedactorDetailView.as_view(), name="redactor-detail"),
    path("redactors/", RedactorListView.as_view(), name="redactor-list"),
    path("redactors/<int:pk>/", RedactorDetailView.as_view(), name="redactor-detail"),
    path("redactors/create/", RedactorCreateView.as_view(), name="redactor-create"),
    path(
        "redactors/<int:pk>/update/",
        RedactorUpdateView.as_view(),
        name="redactor-update",
    ),
    path(
        "redactors/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete",
    ),
]

app_name = "agency"

inform_agency/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("agency.urls", namespace="agency")),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

templates/includes/navbar.html
{% if user.is_authenticated %}
  <nav
      class="navbar navbar-expand-lg navbar-dark bg-gradient-dark z-index-3 py-3">
    <div class="container">
      <a class="navbar-brand text-white text-uppercase" href="{% url 'agency:index' %}" data-placement="bottom">
        InfoStruct
      </a>
      <span class="text-white ml-3">Welcome, {{ user.get_username }}</span>

      <div class="collapse navbar-collapse w-100 pt-3 pb-2 py-lg-0" id="navigation">
        <ul class="navbar-nav navbar-nav-hover mx-auto">
          <li class="nav-item mx-2">
            <a class="text-white nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center"
               role="button" href="{% url 'agency:topic-list' %}">
              TOPICS
            </a>
          </li>
          <li class="nav-item mx-2">
            <a class="text-white nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center"
               role="button" href="{% url 'agency:redactor-list' %}">
              REDACTORS
            </a>
          </li>
          <li class="nav-item mx-2">
            <a class="text-white nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center"
               role="button" href="{% url 'agency:newspaper-list' %}">
              NEWSPAPERS
            </a>
          </li>
        </ul>

        <ul class="navbar-nav d-lg-block d-none">
          <li class="nav-item">
            <form method="post" action="{% url 'logout' %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-sm  btn-dark  btn-round mb-0 me-1">logout</button>
            </form>
          </li>
        </ul>
      </div>
    </div>
  </nav>

{% else %}
  <nav
      class="navbar navbar-expand-lg navbar-dark bg-gradient-dark z-index-3 py-3">
    <div class="container">
      <span class="navbar-brand text-white text-uppercase">InfoStruct</span>

      <a class="btn btn-sm  btn-dark  btn-round mb-0 me-1"
         role="button" href="https://github.com/FanniMalevych/inform-agency"
         target="_blank"
      >
        GitHub project
      </a>
    </div>
  </nav>

{% endif %}

templates/includes/pagination.html
{% load query_transform %}

{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link bg-gradient-dark">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/search_form.html
<form class="form-inline d-flex align-items-start" action="" method="get">
  {{ search_form.as_p }}
  <input class="form-control" type="submit" value="🔍">
</form>